theme: jekyll-theme-cayman
# Site settings
title: You Blog    				  	#你博客的标题
SEOTitle: tangwaikei    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: tagnwaikei2013@gmail.com	
description: "You Blog"  			 #网站介绍
keyword: "tangwaikei" #关键词
url: "https://tangwaikei.github.io"          # 这个就是填写你的博客地址